name: demon
version: 1.0.0-beta
description: Configuration-based, standalone HTTP server.
author: Tobe O <thosakwe@gmail.com>
homepage:
dependencies:
  angel_common: ^1.0.0
dev_dependencies:
  angel_test: ^1.0.0
  test: ^0.12.0